# Generated by Django 5.0.6 on 2024-06-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('registration_date', models.DateField()),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('address', models.TextField()),
                ('contact_person', models.CharField(max_length=255)),
                ('number_of_employees', models.IntegerField()),
                ('contact_phone', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254)),
            ],
        ),
    ]
